arrowParens: always
bracketSpacing: true
endOfLine: 'auto'
jsxBracketSameLine: true
jsxSingleQuote: true
printWidth: 100
quoteProps: 'consistent'
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'
useTabs: true
