# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Merge master -> pages
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout pages branch
        uses: actions/checkout@v2
        with:
          ref: pages
          fetch-depth: 0

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '>=12.17.0'

      - name: Install packages
        run: npm install

      - name: Compile codes
        run: npm run build

      - run: cp ./.nojekyll ./docs

      # TODO: test go here

      - name: Commit to production branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy code for ${{ github.event.head_commit.message }}
          branch: pages
          skip_fetch: true
