# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Compile codes
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      # TODO: test go here

      - name: Commit to production branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy code for ${{ github.event.head_commit.message }}
          branch: production
          file_pattern: build/*
          skip_fetch: true
