name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Merge master -> pages
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout pages branch
        uses: actions/checkout@v2
        with:
          ref: pages
          fetch-depth: 0

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Purge node_modules
        run: rm -rf node_modules

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Disable Jekyll
        run: cp ./.nojekyll ./docs

      # TODO: test go here

      - name: Commit to production branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy code for ${{ github.event.head_commit.message }}
          branch: pages
          skip_fetch: true
